[package]
name = "basic_shellcode_loader_in_rust"
version = "0.1.0"
edition = "2024"

[dependencies.windows-sys]
version = "0.59"
features = [
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Memory"
]

